### ISSUE TITLE
get_cell_template_name bug (_init_.py line 32)

### ISSUE THREAD

**Issue by sunzhenyang2018** [JustasB/hoc2swc#1]
Hi,

get_cell_template_name function requires some string in the hoc file to match the regular expression 'begintemplate (.*)'
I don't think every cell model contains this begintemplate line. Apparently, mine doesn't. 

(I am still able to convert to swc by going into the gui and load my hoc file into an nml first and then use your neuroml2swc function. So, thank you for making that a separate function)

**Comment by JustasB** [comment]
Hi @sunzhenyang2018, Thanks for reporting the bug. If possible, could you attach an example of the hoc file, so I could test the fix?

**Comment by sunzhenyang2018** [comment]
Hi @JustasB . I need to contact my PI first to see whether I am allowed to share it with you. I will tell you when she responds.

**Comment by JustasB** [comment]
Not a problem. I could work even with a stripped down version of the file, with all the sensitive info removed and with only one or few sections.

**Comment by sunzhenyang2018** [comment]
She told me it is ok for me to send you the full version. (github doesn't support hoc so I put it in a zip file)
[Cell1.zip](https://github.com/JustasB/hoc2swc/files/4943969/Cell1.zip)

**Comment by JustasB** [comment]
Thank you! Looking into the issue

**Comment by JustasB** [comment]
Hmm the file looks ok. I fixed an issue where there is an error if the hoc file does not use any custom mod files, but that seems different from the `begintemplate` issue.

Can you try getting the latest version with:

`pip install hoc2swc==0.1.2`

and then running these lines in python (from the folder where the Cell1.hoc is located):

```
import hoc2swc
hoc2swc.hoc2swc("Cell1.hoc", "test.swc", no_mod=True)
```

When I run it, it creates an SWC file that looks like this: 
![image](https://user-images.githubusercontent.com/10732358/87880973-0a315680-c9c4-11ea-8ddd-9b2da731da4c.png)


I get the same result when I do it using `nrniv`, e.g.:

`nrniv -python hoc2swc.py -Cell1.hoc -test.swc`

Can you give these a try, and see if the original issue still comes up?

**Comment by sunzhenyang2018** [comment]
It works now! I think maybe the old issue was due to me having older version (0.1.1) of hoc2swc.

**Comment by JustasB** [comment]
Ok glad to hear its working :)
